---
apiVersion: v1 
kind: ConfigMap 

metadata:
  name: my-configmap 
data:
  MYSQL_ROOT_PASSWORD: "12345"
...
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: mariadb 
  labels:
    app: my-database 
spec: 
  containers: 
  - name: mariadb
    image: mariadb
    ports:
    - name: mariadb
      containerPort: 3306
    env:
        - configMapRef:
            name: my-configmap 
            key: MYSQL_ROOT_PASSWORD
...