---
apiVersion: v1 
kind: ConfigMap 

metadata:
  name: my-configmap 
data:
  MYSQL_ROOT_PASSWORD: "12345"
...
---
apiVersion: v1 
kind: Pod 
metadata:
  name: my-pod
spec:
  containers:
    - name: mariadb
      image: mariadb
      envFrom:
        - configMapRef:
            name: my-configmap

...