---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment2
  labels:
    app: mobile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mobile
  template:
    metadata:
      labels:
        app: mobile
    spec:
      containers:
      - name: nginx
        image: deepakumre/homepage
        ports:
        - containerPort: 80
...
---
apiVersion: v1
kind: Service
metadata:
  name: my-service2
spec:
  type: NodePort
  selector:
      app: mobile
  ports:
    - port: 80
      targetPort: 80
...
