apiVersion: v1
kind: Pod
metadata:
  name: pod5
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  -name:tomcat
   image: tomcat
   ports:
   - containerPort:8080
