---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - name: http
      containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  containers:
  - name: tomcat
    image: tomcat:latest
    ports:
    - name: tomcat
      containerPort: 8080
---
apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: my-replica
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      app: tomcat
...