apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: app, operator: NotIn, values: [my-app]}
  template:
    metadata:
      labels:
        app: my-app
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
