---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment3
  labels:
    app: desktop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: desktop
  template:
    metadata:
      labels:
        app: desktop
    spec:
      containers:
      - name: nginx
        image: deepakumre/homepage
        ports:
        - containerPort: 80
...
---
apiVersion: v1
kind: Service
metadata:
  name: my-service3
spec:
  type: NodePort
  selector:
      app: desktop
  ports:
    - port: 80
      targetPort: 80
...
